# WordPress Sync Workflow
#
# Automatically syncs blog posts to WordPress when pushed to the review folder.
#
# This workflow creates DRAFTS in WordPress - you still need to manually
# review and publish in WordPress admin.
#
# SETUP REQUIRED:
# 1. Create WordPress Application Password:
#    - WordPress Admin → Users → Your Profile → Application Passwords
#    - Create new password, copy it
#
# 2. Add secrets to this repository:
#    - WORDPRESS_URL: Your site URL (e.g., https://yourblog.com)
#    - WORDPRESS_USER: Your WordPress username
#    - WORDPRESS_APP_PASSWORD: The application password

name: Sync to WordPress

on:
  # Trigger when files are pushed to blog/review/
  push:
    paths:
      - 'blog/review/*.md'
    branches:
      - main
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      file:
        description: 'Specific file to sync (e.g., blog/review/my-post.md)'
        required: false
        type: string
      publish:
        description: 'Publish immediately (not just draft)'
        required: false
        type: boolean
        default: false

jobs:
  sync-posts:
    runs-on: ubuntu-latest
    
    # Only run if WordPress credentials are configured
    if: ${{ vars.WORDPRESS_CONFIGURED == 'true' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Need previous commit to detect changes

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Get changed files
        id: changed-files
        run: |
          if [ -n "${{ github.event.inputs.file }}" ]; then
            # Manual trigger with specific file
            echo "files=${{ github.event.inputs.file }}" >> $GITHUB_OUTPUT
          else
            # Get files changed in this push
            FILES=$(git diff --name-only HEAD~1 HEAD -- 'blog/review/*.md' | tr '\n' ' ')
            echo "files=$FILES" >> $GITHUB_OUTPUT
          fi

      - name: Sync posts to WordPress
        if: steps.changed-files.outputs.files != ''
        env:
          WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
          WORDPRESS_USER: ${{ secrets.WORDPRESS_USER }}
          WORDPRESS_APP_PASSWORD: ${{ secrets.WORDPRESS_APP_PASSWORD }}
        run: |
          PUBLISH_FLAG=""
          if [ "${{ github.event.inputs.publish }}" == "true" ]; then
            PUBLISH_FLAG="--publish"
          fi
          
          for file in ${{ steps.changed-files.outputs.files }}; do
            if [ -f "$file" ]; then
              echo "📄 Processing: $file"
              python scripts/publish_to_wordpress.py "$file" $PUBLISH_FLAG
            fi
          done

      - name: Commit updated content calendar
        run: |
          git config --global user.name "Knowledge Vault Bot"
          git config --global user.email "bot@noreply.github.com"
          git add blog/content-calendar.json
          git diff --staged --quiet || git commit -m "docs: update content calendar [skip ci]"
          git push

      - name: Summary
        run: |
          echo "## WordPress Sync Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Files processed:** ${{ steps.changed-files.outputs.files }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Posts have been created as **drafts** in WordPress." >> $GITHUB_STEP_SUMMARY
          echo "Review and publish them in your WordPress admin." >> $GITHUB_STEP_SUMMARY
